enabled: true

# Refer to https://jd.papermc.io/paper/1.21.11-pre3/org/bukkit/Material.html
# for all possible objects
# If the material isn't a block then it will effectively do nothing as it can't be placed
functional-materials:
  - CHEST
  - TRAPPED_CHEST
  - COPPER_CHEST
  - OXIDIZED_COPPER_CHEST
  - WAXED_COPPER_CHEST
  - WAXED_EXPOSED_COPPER_CHEST
  - WAXED_OXIDIZED_COPPER_CHEST
  - WAXED_WEATHERED_COPPER_CHEST
  - WEATHERED_COPPER_CHEST